---
  - name: Update apt
    apt: update_cache=yes
    become: yes
    become_method: sudo

  - name: Install core packages
    apt: pkg={{ item }} state=latest
    become: yes
    become_method: sudo
    with_items:
      - build-essential
      - git
      - curl
      - wget
      - python-software-properties
      - software-properties-common